[package]
name = "More Console Commands"
description = "a collection of commonly used console commands via UI Expansion Lua console for Morrowind."
homepage = "https://www.nexusmods.com/morrowind/mods/52500"
repository = "https://github.com/amaliegay/more-console-commands"
authors = [ "JosephMcKean",]
version = "1.10"

[dependencies]
assets = [ "MWSE/mods/JosephMcKean/commands",]

[dependencies.mwse]
buildnumber = 3147

[dependencies.mods."UI Expansion"]
mwse-module = "UI Expansion"
url = "https://www.nexusmods.com/morrowind/mods/46071"